# theme: minimal
# remote-theme: poole/lanyon@v1.1.0
# remote-theme: daviddarnes/garth # See https://github.com/daviddarnes/garth/blob/master/_config.yml
remote-theme: patdryburgh/hitchens
plugins:
- jekyll-remote-theme

# Site settings
encoding: utf-8 # Make sure the encoding is right
title: "2025 Year in Review: AI measurement science"
# logo: "/assets/logo.svg" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
# description: "A really basic theme for Jekyll, using the official Jekyll theme implementation" # Site description and default description
url: "https://ai-metrology.github.io/review-2025" # Site url
baseurl: ""
lang: en-US
